# Generated by Django 4.0.3 on 2022-03-13 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='createdd',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updadted',
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 7, 57, 58, 15272, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
